package com.prod.todo.unit.mapper;

import com.prod.todo.entity.TodoEntity;
import com.prod.todo.mapper.TodoMapper;
import com.prod.todo.mapper.TodoMapperHelper;
import com.prod.todo.model.Todo;
import org.instancio.Instancio;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mapstruct.factory.Mappers;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = TodoMapperSpringTest.Config.class)
class TodoMapperSpringTest {

    private final TodoMapper todoMapper = Mappers.getMapper(TodoMapper.class);

    @Configuration
    @ComponentScan(basePackageClasses = TodoMapper.class)
    static class Config {
    }

    @Test
    @DisplayName("Should map entity to model with formatted locale timestamps")
    void toModelWithLocale_ShouldMapTimestampsWithFormattedStrings() {

        TodoEntity entity = Instancio.of(TodoEntity.class)
                .create();

        Todo result = todoMapper.toModelWithLocale(entity);

        assertThat(result).isNotNull();
        assertThat(result.getLocaleCreatedAt()).isEqualTo(TodoMapperHelper.formatLocale(entity.getCreatedAt()));
        assertThat(result.getLocaleUpdatedAt()).isEqualTo(TodoMapperHelper.formatLocale(entity.getUpdatedAt()));
    }

    @Test
    @DisplayName("Should ignore generated fields when mapping to new entity")
    void toNewEntity_ShouldIgnoreAutoGeneratedFields() {

        Todo todo = Instancio.of(Todo.class).create();

        TodoEntity result = todoMapper.toNewEntity(todo);

        assertThat(result).isNotNull();
        assertThat(result.getId()).isNull();
        assertThat(result.getCreatedAt()).isNull();
        assertThat(result.getCreatedBy()).isNull();
        assertThat(result.getUpdatedAt()).isNull();
        assertThat(result.getUpdatedBy()).isNull();
        assertThat(result.getVersion()).isNull();
    }

    @Test
    @DisplayName("Should map list of entities to list of models with locale")
    void toModelListWithLocale_ShouldMapListCorrectly() {

        TodoEntity entity = Instancio.create(TodoEntity.class);

        List<Todo> result = todoMapper.toModelListWithLocale(List.of(entity));

        assertThat(result).hasSize(1);
        assertThat(result.getFirst()).isNotNull();
    }

}
